/* Generated By:JJTree&JavaCC: Do not edit this line. MultiSQLPaserConstants.java */
package test;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MultiSQLPaserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 5;
  /** RegularExpression Id. */
  int WHERE = 6;
  /** RegularExpression Id. */
  int FROM = 7;
  /** RegularExpression Id. */
  int JOIN = 8;
  /** RegularExpression Id. */
  int LIKE = 9;
  /** RegularExpression Id. */
  int GROUP = 10;
  /** RegularExpression Id. */
  int ORDER = 11;
  /** RegularExpression Id. */
  int BY = 12;
  /** RegularExpression Id. */
  int VALUES = 13;
  /** RegularExpression Id. */
  int AND = 14;
  /** RegularExpression Id. */
  int OR = 15;
  /** RegularExpression Id. */
  int AS = 16;
  /** RegularExpression Id. */
  int IN = 17;
  /** RegularExpression Id. */
  int COUNT = 18;
  /** RegularExpression Id. */
  int SUM = 19;
  /** RegularExpression Id. */
  int AVG = 20;
  /** RegularExpression Id. */
  int MAX = 21;
  /** RegularExpression Id. */
  int MIN = 22;
  /** RegularExpression Id. */
  int BETWEEN = 23;
  /** RegularExpression Id. */
  int INIT = 24;
  /** RegularExpression Id. */
  int RULE = 25;
  /** RegularExpression Id. */
  int MATCH = 26;
  /** RegularExpression Id. */
  int LIST = 27;
  /** RegularExpression Id. */
  int WITH = 28;
  /** RegularExpression Id. */
  int UNDERSCORE = 29;
  /** RegularExpression Id. */
  int COMMA = 30;
  /** RegularExpression Id. */
  int POINT = 31;
  /** RegularExpression Id. */
  int SEMICOLON = 32;
  /** RegularExpression Id. */
  int ALL = 33;
  /** RegularExpression Id. */
  int NEG = 34;
  /** RegularExpression Id. */
  int LEFTPARENTHESES = 35;
  /** RegularExpression Id. */
  int RIGHTPARENTHESES = 36;
  /** RegularExpression Id. */
  int EQUAL = 37;
  /** RegularExpression Id. */
  int LQUOTATION = 38;
  /** RegularExpression Id. */
  int LEFTQUOTATION = 39;
  /** RegularExpression Id. */
  int HIGHER = 40;
  /** RegularExpression Id. */
  int LOWER = 41;
  /** RegularExpression Id. */
  int EHIGHER = 42;
  /** RegularExpression Id. */
  int ELOWER = 43;
  /** RegularExpression Id. */
  int LEFTREL = 44;
  /** RegularExpression Id. */
  int RIGHTREL = 45;
  /** RegularExpression Id. */
  int LEFTPAREN = 46;
  /** RegularExpression Id. */
  int RIGHTPAREN = 47;
  /** RegularExpression Id. */
  int COLON = 48;
  /** RegularExpression Id. */
  int LEFTBRACKET = 49;
  /** RegularExpression Id. */
  int RIGHTBRACKET = 50;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 51;
  /** RegularExpression Id. */
  int LITERAL = 52;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 53;
  /** RegularExpression Id. */
  int STRDIGITS = 54;
  /** RegularExpression Id. */
  int DIGIT = 55;
  /** RegularExpression Id. */
  int IDENTIFIER = 56;
  /** RegularExpression Id. */
  int LETTER = 57;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"Select\"",
    "\"where\"",
    "\"from\"",
    "\"Join\"",
    "\"like\"",
    "\"group\"",
    "\"order\"",
    "\"by\"",
    "\"values\"",
    "\"and\"",
    "\"or\"",
    "\"as\"",
    "\"in\"",
    "\"count\"",
    "\"sum\"",
    "\"avg\"",
    "\"max\"",
    "\"min\"",
    "\"between\"",
    "\"init\"",
    "\"rule\"",
    "\"match\"",
    "\"list\"",
    "\"with\"",
    "\"_\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"*\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\">\"",
    "\"< \"",
    "\">=\"",
    "\"<=\"",
    "\"<-\"",
    "\"->\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "<INTEGER_LITERAL>",
    "<LITERAL>",
    "<FLOAT_LITERAL>",
    "<STRDIGITS>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<LETTER>",
  };

}
