/* Generated By:JavaCC: Do not edit this line. MultiSQLPaserTreeConstants.java Version 5.0 */
package test;

public interface MultiSQLPaserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTQUERY = 2;
  public int JJTSUFFIX = 3;
  public int JJTSFW = 4;
  public int JJTSINGLEATTSFW = 5;
  public int JJTSELECTLIST = 6;
  public int JJTSELECTITEM = 7;
  public int JJTJOINCELL = 8;
  public int JJTJOINSINGLE = 9;
  public int JJTJOINRULE = 10;
  public int JJTDOC = 11;
  public int JJTJOINITEMLIST = 12;
  public int JJTJOINATTRCONDITION = 13;
  public int JJTEQUCONDITION = 14;
  public int JJTJOINITEM = 15;
  public int JJTJOINEQUCONDITION = 16;
  public int JJTFUNC = 17;
  public int JJTCONDITIONS = 18;
  public int JJTCONDITION = 19;
  public int JJTACTION = 20;
  public int JJTGRAPHCON = 21;
  public int JJTGRAOB = 22;
  public int JJTBLOGMATCH = 23;
  public int JJTMATCHCON = 24;
  public int JJTMATCHOB = 25;
  public int JJTLISTOB = 26;
  public int JJTOBJECT = 27;
  public int JJTTRIPLE = 28;
  public int JJTOPTION = 29;
  public int JJTPATH = 30;
  public int JJTFROMCLAUSE = 31;
  public int JJTEQUAL = 32;
  public int JJTBETWEEN = 33;
  public int JJTIN = 34;
  public int JJTANGLEBRACKET = 35;
  public int JJTARROW = 36;
  public int JJTHIGHER = 37;
  public int JJTLOWER = 38;
  public int JJTJOINNAME = 39;
  public int JJTATTRIBUTE = 40;
  public int JJTRELATION = 41;
  public int JJTPATTERN = 42;
  public int JJTCOMPARE = 43;
  public int JJTIDENTIFIER = 44;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "Query",
    "SUFFIX",
    "SFW",
    "SingleAttSFW",
    "SelectList",
    "SelectItem",
    "JoinCell",
    "JoinSingle",
    "Joinrule",
    "doc",
    "JoinItemList",
    "JoinAttrCondition",
    "EquCondition",
    "JoinItem",
    "JoinEquCondition",
    "Func",
    "Conditions",
    "Condition",
    "Action",
    "Graphcon",
    "Graob",
    "Blogmatch",
    "Matchcon",
    "Matchob",
    "Listob",
    "Object",
    "triple",
    "option",
    "Path",
    "Fromclause",
    "Equal",
    "Between",
    "In",
    "Anglebracket",
    "Arrow",
    "Higher",
    "Lower",
    "Joinname",
    "Attribute",
    "Relation",
    "Pattern",
    "Compare",
    "IDENTIFIER",
  };
}
/* JavaCC - OriginalChecksum=ed0b972bf7d4fc88497f87e652cdd2f9 (do not edit this line) */
